debug: false
agent_mode: "voice" #voice, text
agent_tts_model: "eleven_multilingual_v2"
agent_tts_voice: "JBFqnCBsd6RMkjVDRZzb"
agent_tts_clean_model: "gpt-4o-mini"
agent_stt_model: "nova-3"
agent_chat_provider: null
agent_chat_model: "gpt-4.1"
agent_realtime_model: "gpt-4o-realtime-preview"
agent_realtime_voice: "alloy"
client_tts_model: "eleven_multilingual_v2"
client_tts_voice: "56AoDkrOh6qfVPDXZ7Pt"
environment: "order_management"
entries: [0]
metrics: ["accuracy"]
noises: []
noise_volume: 5
num_threads: 10
max_turns: 8
sample_rate: 24000
cutoff_freq: 0
clipping_threshold: 0
drop_probability: 0
chunk_size_ms: 100
snr_db: 0
task_iterations: 1
termination_timer: 600
