debug: false
agent_mode: "text" 
agent_tts_model: "sonic"
agent_tts_voice: "694f9389-aac1-45b6-b726-9d9369183238"
agent_tts_clean_model: "gpt-4o-mini"
agent_stt_model: "nova-3"
agent_openai_compatible_chat_model: false
agent_openai_compatible_base_url: ""
agent_openai_compatible_api_key: ""
agent_chat_model: "gpt-4o"
agent_realtime_model: "gpt-4o-realtime-preview"
agent_realtime_voice: "alloy"
environment: "appointments_management"              
entries: [-1]
metrics: ["accuracy"]
noises: []
noise_volume: 5
num_threads: 10
max_turns: 30
sample_rate: 24000
cutoff_freq: 0
clipping_threshold: 0
drop_probability: 0
chunk_size_ms: 100
snr_db: 0
task_iterations: 1
